#!/bin/sh

# 运行代码检查
echo "Running linting..."
black .  # 直接格式化文件，而不是检查
LINT_RESULT=$?

if [ $LINT_RESULT -ne 0 ]; then
    echo "❌ Formatting failed. 格式化过程中出错，请重试。"
    exit 1
fi

# 运行代码格式化（这一步可以省略，因为上面已经格式化过了）
# echo "Running formatting..."
# black .
# FORMAT_RESULT=$?
# ...

# 如果有文件被重新格式化，将它们重新添加到暂存区
git diff --name-only | xargs -I {} git add "{}"

echo "✅ Pre-commit checks passed!"
exit 0